import type { ElfAvatar } from "@/db/schema";
export type ElfSeed = {
  name: string;
  gender: "boy" | "girl";
  bio: string;
  personality: string;
  hobbies: string;
  christmasJob: string;
  favoriteTreat: string;
  funFact: string;
  avatar: ElfAvatar;
};
export const ELF_SEEDS: ElfSeed[] = [
  {
    name: "Jingle",
    gender: "boy",
    bio: "Jingle is the workshop’s resident comedian. He can turn a tangled string of lights into a giggle storm and never lets a gloomy morning last.",
    personality: "Funny, playful, and endlessly encouraging",
    hobbies: "Sledding, knock-knock jokes, and racing paper airplanes down the toy chute",
    christmasJob: "Makes wooden toys and tests the squeaky ones",
    favoriteTreat: "Peppermint bark stacked extra high",
    funFact: "His hat bell rings in a different note depending on his mood.",
    avatar: {
      skin: "#f3c7a3",
      hat: "#c4122f",
      hair: "#3b2416",
      outfit: "#0f8a4b",
      accent: "#f0c75e",
      eye: "#2a1a12",
      accessory: "bells",
    },
  },
  {
    name: "Spark",
    gender: "boy",
    bio: "Spark lights up every room—sometimes literally. He is in charge of the sparkle dust and believes every letter deserves fireworks of kindness.",
    personality: "Energetic, bold, and wildly imaginative",
    hobbies: "Snow fireworks, drumming on gift boxes, and inventing glow-in-the-dark stickers",
    christmasJob: "Wraps presents with extra-shiny ribbons",
    favoriteTreat: "Hot cocoa with popping candy",
    funFact: "He once wrapped a present so shiny it was mistaken for the North Star.",
    avatar: {
      skin: "#e8b894",
      hat: "#e11d48",
      hair: "#1f140c",
      outfit: "#14532d",
      accent: "#facc15",
      eye: "#111827",
      accessory: "none",
    },
  },
  {
    name: "Frost",
    gender: "boy",
    bio: "Frost is calm as a frozen lake and twice as sparkly. He sculpts ice animals for the reindeer garden and writes letters in careful, twinkly script.",
    personality: "Gentle, thoughtful, and quietly funny",
    hobbies: "Ice sculpting, stargazing, and listening to snow fall",
    christmasJob: "Polishes Santa’s sleigh until it mirrors the aurora",
    favoriteTreat: "Blueberry snow cream",
    funFact: "He can tell tomorrow’s weather by tasting a single snowflake.",
    avatar: {
      skin: "#f8d7c4",
      hat: "#164e63",
      hair: "#94a3b8",
      outfit: "#0f766e",
      accent: "#e0f2fe",
      eye: "#0e7490",
      accessory: "glasses",
    },
  },
  {
    name: "Cocoa",
    gender: "boy",
    bio: "Cocoa is the warmest hug at the North Pole. He keeps a kettle singing and a story ready for any elf (or child) who needs cheering up.",
    personality: "Warm, wise, and cozy",
    hobbies: "Storytelling, marshmallow science, and knitting tiny scarves",
    christmasJob: "Stirs the official workshop cocoa cauldron",
    favoriteTreat: "Marshmallows toasted over cinnamon sticks",
    funFact: "He knows 77 ways to say ‘goodnight’ in cookie crumbs.",
    avatar: {
      skin: "#c9855a",
      hat: "#7f1d1d",
      hair: "#1c1917",
      outfit: "#78350f",
      accent: "#f5d0a6",
      eye: "#431407",
      accessory: "scarf",
    },
  },
  {
    name: "Twinkle",
    gender: "boy",
    bio: "Twinkle hangs the workshop lights and talks to constellations like old friends. He believes every child has a star with their name on it.",
    personality: "Dreamy, kind, and a little mischievous",
    hobbies: "Stargazing, light-string puzzles, and collecting shiny buttons",
    christmasJob: "Hangs twinkling lights across Santa’s village",
    favoriteTreat: "Sugar-cookie stars with gold sprinkle belts",
    funFact: "He once used a firefly as a night-light for a homesick teddy bear.",
    avatar: {
      skin: "#f1c19a",
      hat: "#be123c",
      hair: "#92400e",
      outfit: "#166534",
      accent: "#fde68a",
      eye: "#1e293b",
      accessory: "none",
    },
  },
  {
    name: "Biscuit",
    gender: "boy",
    bio: "Biscuit is flour-dusted, giggle-prone, and the official taste-tester of almost everything. Crumbs follow him like a friendly snow trail.",
    personality: "Goofy, generous, and cheerful",
    hobbies: "Baking, cookie decorating, and pancake-flipping contests",
    christmasJob: "Quality-checks the Christmas cookies",
    favoriteTreat: "Gingerbread with extra icing buttons",
    funFact: "He once baked a cookie so big the reindeer used it as a sled.",
    avatar: {
      skin: "#efc2a0",
      hat: "#9f1239",
      hair: "#78350f",
      outfit: "#365314",
      accent: "#fdba74",
      eye: "#44403c",
      accessory: "none",
    },
  },
  {
    name: "Pine",
    gender: "boy",
    bio: "Pine smells like a Christmas tree lot in the best way. He hikes the snowy hills looking for the perfect evergreens and secret animal trails.",
    personality: "Adventurous, loyal, and brave",
    hobbies: "Tree climbing, map drawing, and animal tracking",
    christmasJob: "Chooses Christmas trees for the village square",
    favoriteTreat: "Maple candy on a stick",
    funFact: "A family of snow hares follows him everywhere like a fluffy parade.",
    avatar: {
      skin: "#e2b48c",
      hat: "#14532d",
      hair: "#292524",
      outfit: "#1f2937",
      accent: "#86efac",
      eye: "#365314",
      accessory: "scarf",
    },
  },
  {
    name: "Ember",
    gender: "boy",
    bio: "Ember keeps the workshop toasty when blizzards howl. He is brave, spark-hearted, and always ready with a warm pair of mittens.",
    personality: "Brave, protective, and fiery-kind",
    hobbies: "Keeping fires, toasting chestnuts, and lantern making",
    christmasJob: "Tends the workshop hearths and warms mittens",
    favoriteTreat: "Cinnamon sticks dipped in chocolate",
    funFact: "His lantern never goes out, even in the wildest storm.",
    avatar: {
      skin: "#d09263",
      hat: "#991b1b",
      hair: "#0c0a09",
      outfit: "#7c2d12",
      accent: "#fb923c",
      eye: "#7c2d12",
      accessory: "none",
    },
  },
  {
    name: "Dash",
    gender: "boy",
    bio: "Dash is the fastest mail elf in the polar post. He zips between workshops with letters, stickers, and news from the reindeer stables.",
    personality: "Quick, peppy, and super encouraging",
    hobbies: "Racing, obstacle courses, and origami airplanes",
    christmasJob: "Delivers workshop mail and wish-list notes",
    favoriteTreat: "Candy canes snapped into lightning-bolt pieces",
    funFact: "He can ice-skate faster than a snowstorm sneeze.",
    avatar: {
      skin: "#f4c9a8",
      hat: "#dc2626",
      hair: "#451a03",
      outfit: "#0369a1",
      accent: "#fbbf24",
      eye: "#0f172a",
      accessory: "bells",
    },
  },
  {
    name: "Noel",
    gender: "boy",
    bio: "Noel writes carols the toys can hum along to. Soft-spoken and sincere, he believes music is just another way to send a hug.",
    personality: "Gentle, artistic, and sincere",
    hobbies: "Songwriting, humming, and teaching teddy bears to choir",
    christmasJob: "Composes lullabies for the toy nursery",
    favoriteTreat: "Fruitcake crumbs with sparkling sugar",
    funFact: "His favorite carol changes every time it snows.",
    avatar: {
      skin: "#efd0b5",
      hat: "#9f1239",
      hair: "#a8a29e",
      outfit: "#1e3a5f",
      accent: "#f5d0fe",
      eye: "#334155",
      accessory: "glasses",
    },
  },
  {
    name: "Holly",
    gender: "girl",
    bio: "Holly is sweet as a gumdrop and twice as helpful. She bakes welcome cookies for new pen pals and never forgets a favorite color.",
    personality: "Sweet, caring, and wonderfully encouraging",
    hobbies: "Baking cookies, braiding ribbons, and feeding the reindeer",
    christmasJob: "Feeds the reindeer and braids their festive manes",
    favoriteTreat: "Gumdrops in every color of the aurora",
    funFact: "Rudolph lets her borrow his nose-glow as a night-light.",
    avatar: {
      skin: "#f6cbb0",
      hat: "#be123c",
      hair: "#7c2d12",
      outfit: "#15803d",
      accent: "#f0c75e",
      eye: "#3f2a1d",
      accessory: "bow",
    },
  },
  {
    name: "Sugar",
    gender: "girl",
    bio: "Sugar paints smiles onto nutcrackers and believes sprinkles are a food group. Her laugh sounds like wind chimes in a snowstorm.",
    personality: "Cheerful, creative, and bubbly",
    hobbies: "Decorating, glitter art, and cupcake architecture",
    christmasJob: "Paints nutcrackers and toy soldiers",
    favoriteTreat: "Peppermint swirls with extra sparkle sugar",
    funFact: "She invented glow-in-the-dark frosting by accident.",
    avatar: {
      skin: "#f8d5c0",
      hat: "#fb7185",
      hair: "#f59e0b",
      outfit: "#9d174d",
      accent: "#fecdd3",
      eye: "#9f1239",
      accessory: "bow",
    },
  },
  {
    name: "Belle",
    gender: "girl",
    bio: "Belle sews tiny coats for dolls and even tinier pockets for secret notes. She is kind, patient, and an excellent keeper of wishes.",
    personality: "Kind, patient, and graceful",
    hobbies: "Sewing, embroidery, and reading bedtime stories to dolls",
    christmasJob: "Makes doll clothes and quilted stockings",
    favoriteTreat: "Chocolate coins wrapped in gold foil",
    funFact: "Every coat she sews has a hidden pocket for a wish.",
    avatar: {
      skin: "#edc4a4",
      hat: "#b91c1c",
      hair: "#1c1917",
      outfit: "#6b21a8",
      accent: "#fde68a",
      eye: "#44403c",
      accessory: "none",
    },
  },
  {
    name: "Ivy",
    gender: "girl",
    bio: "Ivy tends the North Pole greenhouse where holly, cocoa beans, and candy blossoms grow. Curious about everything, she asks the best questions.",
    personality: "Curious, clever, and kind",
    hobbies: "Gardening, collecting leaves, and naming snowflakes",
    christmasJob: "Grows holly, mistletoe, and peppermint plants",
    favoriteTreat: "Peppermint tea with honey snow",
    funFact: "She once grew a candy-cane vine that rang like bells.",
    avatar: {
      skin: "#e4b894",
      hat: "#166534",
      hair: "#365314",
      outfit: "#064e3b",
      accent: "#86efac",
      eye: "#14532d",
      accessory: "glasses",
    },
  },
  {
    name: "Stella",
    gender: "girl",
    bio: "Stella paints stars on toys so children can take a piece of the night sky home. She is dreamy, poetic, and a little bit cosmic.",
    personality: "Dreamy, poetic, and imaginative",
    hobbies: "Aurora watching, painting galaxies, and cloud spotting",
    christmasJob: "Paints stars and constellations on wooden toys",
    favoriteTreat: "Star cookies dusted with edible gold",
    funFact: "She claims the aurora hums lullabies if you listen with mittens on.",
    avatar: {
      skin: "#f3c8b0",
      hat: "#1e1b4b",
      hair: "#312e81",
      outfit: "#4c1d95",
      accent: "#c4b5fd",
      eye: "#312e81",
      accessory: "none",
    },
  },
  {
    name: "Ginger",
    gender: "girl",
    bio: "Ginger is the wrapping-paper whirlwind of Workshop Seven. Spunky and inventive, she can turn any box into a celebration.",
    personality: "Spunky, inventive, and hilarious",
    hobbies: "Gift wrapping, bow sculpting, and treasure hunts",
    christmasJob: "Invents new bow styles and wrapping tricks",
    favoriteTreat: "Ginger snaps dunked in cocoa",
    funFact: "She can wrap a present using only one ribbon and a wink.",
    avatar: {
      skin: "#e8b086",
      hat: "#ea580c",
      hair: "#9a3412",
      outfit: "#9f1239",
      accent: "#fdba74",
      eye: "#7c2d12",
      accessory: "bow",
    },
  },
  {
    name: "Merry",
    gender: "girl",
    bio: "Merry leads the elf choir and can turn a quiet hallway into a dance floor. She believes joy is contagious—and she is living proof.",
    personality: "Bubbly, musical, and sunny",
    hobbies: "Dancing, choir practice, and jingle-bell aerobics",
    christmasJob: "Leads the elf choir and holiday parades",
    favoriteTreat: "Peppermint swirl ice cream",
    funFact: "Snowmen sway whenever she sings nearby.",
    avatar: {
      skin: "#f0c2a6",
      hat: "#e11d48",
      hair: "#b45309",
      outfit: "#047857",
      accent: "#fef08a",
      eye: "#9f1239",
      accessory: "bells",
    },
  },
  {
    name: "Snowflake",
    gender: "girl",
    bio: "Snowflake speaks softly and sparkles loudly. She polishes ornaments until they hold tiny reflections of tomorrow’s joy.",
    personality: "Soft-spoken, magical, and tender-hearted",
    hobbies: "Catching snowflakes, ornament polishing, and quiet drawing",
    christmasJob: "Polishes ornaments for the great tree",
    favoriteTreat: "Vanilla snowball truffles",
    funFact: "No two of her snowflake drawings have ever been the same.",
    avatar: {
      skin: "#f7d8c8",
      hat: "#e2e8f0",
      hair: "#cbd5e1",
      outfit: "#0ea5e9",
      accent: "#f8fafc",
      eye: "#0369a1",
      accessory: "none",
    },
  },
  {
    name: "Ruby",
    gender: "girl",
    bio: "Ruby crash-tests sleds, rockets, and anything with wheels. Bold and bright, she cheers the loudest when kids try something new.",
    personality: "Bold, athletic, and fiercely loyal",
    hobbies: "Sled testing, snowball target practice, and victory dances",
    christmasJob: "Crash-tests sleds and toy racers",
    favoriteTreat: "Cherry drops that fizz like fireworks",
    funFact: "She has a tiny gold medal from the Reindeer Games—for sportsmanship.",
    avatar: {
      skin: "#d PANDA",
      hat: "#9f1239",
      hair: "#111827",
      outfit: "#7f1d1d",
      accent: "#fca5a5",
      eye: "#7f1d1d",
      accessory: "scarf",
    },
  },
  {
    name: "Clara",
    gender: "girl",
    bio: "Clara sorts the world’s wish lists with care. Thoughtful and organized, she remembers the little details that make a friendship feel real.",
    personality: "Thoughtful, organized, and warmly funny",
    hobbies: "Letter sorting, journaling, and pressing holly in books",
    christmasJob: "Reads wish lists and routes them to the right workshop",
    favoriteTreat: "Hot cocoa with extra cream clouds",
    funFact: "She keeps a tiny notebook of the kindest sentences children ever wrote.",
    avatar: {
      skin: "#f0c8ae",
      hat: "#9f1239",
      hair: "#57534e",
      outfit: "#1f2937",
      accent: "#fcd34d",
      eye: "#44403c",
      accessory: "glasses",
    },
  },
];